name: continuous integration

on:
  pull_request:
    paths:
      - '**/src/**'
      - '**/tests/**'
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 👌👌👌👌
        uses: actions/checkout@v2

#      - name: Setup Database 📊📊
#        run: docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Db@123123" -p 1440:1433 -d mcr.microsoft.com/mssql/server:2019-latest
#
      - name: Sleep for 10s 💤💤💤💤💤
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Setup dotnet 🔧🔧🔧🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencis 🔧🔧🔧🔧
        run: dotnet restore

      - name: Build app 🚀
        run: dotnet build -c Release --no-restore

      - name: Unit Test ✅✅✅✅
        run:  dotnet test -c Release --no-build

      - name: Publish app
        run: dotnet publish -c Release -o ./app